using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using Faultline.Core;

namespace Faultline.Web.Tests;

/// <summary>
/// Builds <c>docs/PROGRESSION_REVIEW.md</c> out of Core's own definitions, and fails when the file on
/// disk no longer matches.
/// </summary>
/// <remarks>
/// <para>
/// <b>Generated, not written.</b> Every count in that document is a question Core can already answer —
/// how many mods a class has, which tags no technique carries, whether a duck has anything to learn.
/// Typing those numbers into a markdown file makes them wrong on the next commit that adds a card.
/// </para>
/// <para>
/// <b>Why a test rather than a tool.</b> The doc's whole value is being true, and a generator nobody
/// runs is a doc nobody can trust. As a test it fails the moment the content pool moves, which is the
/// only moment the doc matters. Set <c>PLUCK_WRITE_DOCS=1</c> to rewrite it instead of asserting.
/// </para>
/// </remarks>
public class ProgressionDocTests
{
    private static readonly UnitKind[] Classes =
    {
        UnitKind.Vanguard,
        UnitKind.Archer,
        UnitKind.Threadcaster,
        UnitKind.Wardbearer,
    };

    /// <summary>The doc on disk still says what the code says.</summary>
    [Fact]
    public void TheProgressionDoc_MatchesTheCode()
    {
        var b = new List<string>();

        void W(string line = "") => b.Add(line);

        W("<!-- GENERATED by tools — every table below is read out of Faultline.Core at build time.");
        W("     Regenerate rather than hand-edit; a number typed here is a number that can drift. -->");
        W("");
        W("# PLUCK — what a duck can become");
        W("");
        W("**As-built.** Every table is read straight out of `Faultline.Core`, so this is what the game");
        W("does today, not what the design doc intends. Where the two differ, `DECISIONS.md` says why.");
        W("");
        W("Written to be reviewed: each section ends with **what is thin**, counted rather than felt.");
        W("");

        Progression(W);
        Classes_(W);
        Techniques(W);
        Mods(W);
        SecondWinds(W);
        Unlocks(W);
        Consumables_(W);
        Legendaries(W);
        Totals(W);

        var path = Path.Combine(RepoRoot(), "docs", "PROGRESSION_REVIEW.md");
        var built = string.Join("\n", b).TrimEnd() + "\n";

        if (Environment.GetEnvironmentVariable("PLUCK_WRITE_DOCS") == "1")
        {
            File.WriteAllText(path, built);
            return;
        }

        Assert.True(File.Exists(path), "docs/PROGRESSION_REVIEW.md is missing. Regenerate with PLUCK_WRITE_DOCS=1.");

        // Line endings normalised: this repo checks out CRLF on Windows and the builder joins with LF.
        var onDisk = File.ReadAllText(path).Replace("\r\n", "\n").TrimEnd() + "\n";

        Assert.True(
            string.Equals(onDisk, built, StringComparison.Ordinal),
            "docs/PROGRESSION_REVIEW.md is stale — the content pool moved. "
            + "Regenerate with PLUCK_WRITE_DOCS=1 dotnet test --filter ProgressionDoc.");
    }

    // ---- How a run makes a duck better ---------------------------------------------------------

    private static void Progression(Action<string> W)
    {
        W("## How progression works");
        W("");
        W("A run is a walk across an act's columns. Four things can change a duck, and they are");
        W("deliberately different in kind:");
        W("");
        W("| Where | When | What it hands over | Who chooses |");
        W("|---|---|---|---|");
        W("| **Camp** | after every won combat node | one card per player | each player, from their own table |");
        W("| **Still Pond** | its own node | hit points back, or the Forge | the party |");
        W("| **Event** | its own node | a body trade, priced in HP | each duck's owner |");
        W("| **Destination** | gilt-marked nodes | a permanent legendary | the party |");
        W("");
        W("**The camp is two tables, one pick each** — each table addressed to that player's ducks, and");
        W("the node does not resolve until both are spent. Card tiers are drawn on weights rather than");
        W("branches, and the weights differ by lane:");
        W("");
        W("| Source | Common | Uncommon | Rare |");
        W("|---|---|---|---|");

        foreach (RewardSource source in Enum.GetValues(typeof(RewardSource)))
        {
            var odds = RarityOdds.For(source);
            W("| " + source + " | " + odds.Common + " | " + odds.Uncommon + " | " + odds.Rare + " |");
        }

        W("");
        W("Weights, not percentages: a tier whose pool is empty contributes nothing, so a table is");
        W("never short a card because the dice asked for a tier that has run out.");
        W("");
        W("**Nothing in the camp pool is Rare.** Every Rare the build ships is a destination legendary —");
        W("that is the tier ladder and the reward-source split being the same statement.");
        W("");
        W("**Kit surgery is the shape of a build.** A duck holds a fixed number of ability slots and");
        W("Pluck-spender slots; learning past a full slot means *replacing*, and the card names what it");
        W("replaces. A slot count is per class, not per duck:");
        W("");
        W("| Class | Ability slots | Pluck slots | Starts with |");
        W("|---|---|---|---|");

        foreach (var kind in Classes)
        {
            var kit = Kits.For(kind);
            W("| " + Naming.Of(kind)
                + " | " + kit.AbilitySlots
                + " | " + kit.PluckSlots
                + " | " + kit.Abilities.Count + " abilities, " + kit.Spenders.Count + " spender(s) |");
        }

        W("");
        W("### What is thin");
        W("");
        W("- **The Molt is not built.** Clearing an act grants nothing; the between-runs layer where");
        W("  permanence was supposed to live does not exist yet, so every run starts from the same duck.");
        W("- **Two reward sources are tuned, not three.** `RarityOdds` has a row for the safe camp and");
        W("  the hungry camp. The Forge has no row.");
        W("- **The odds themselves are unplaytested** — locked ladder, unlocked numbers.");
        W("");
    }

    // ---- Per class -----------------------------------------------------------------------------

    private static void Classes_(Action<string> W)
    {
        W("## The four classes");
        W("");

        foreach (var kind in Classes)
        {
            var kit = Kits.For(kind);
            var template = UnitTemplate.For(kind);

            W("### " + Naming.Of(kind));
            W("");
            W("`" + template.MaxHp + " HP · move " + template.Move + " · " + kit.AbilitySlots
                + " ability slots · " + kit.PluckSlots + " Pluck slot(s)`");
            W("");
            W("**Abilities**");
            W("");
            W("| Ability | AP | Range | What it does | Starts held |");
            W("|---|---|---|---|---|");

            // The class's plain swing first. It is a kit entry with no AbilityDefinition behind it, so
            // a table built only from AllForKind silently loses it — and then a class reads as holding
            // more abilities than it knows. Its reach and damage come from the profile rather than
            // being typed, because the Archer's is a band and a hardcoded "1 | 1" would lie about it.
            if (Kits.BasicFor(kind) is { } basic)
            {
                W("| " + Kits.NameOf(basic)
                    + " | 1 | " + Reach(template)
                    + " | " + EnemyBehaviour.Describe(template)
                    + " | yes |");
            }

            foreach (var def in AbilityDefinition.AllForKind(kind))
            {
                var entry = Kits.EntryOf(def.Ability);
                bool starts = kit.Abilities.Contains(entry);

                W("| " + def.Name
                    + " | " + def.Cost
                    + " | " + RangeOf(def)
                    + " | " + def.Summary
                    + " | " + (starts ? "yes" : "—") + " |");
            }

            W("");

            var spenders = Enum.GetValues(typeof(VerveSpend)).Cast<VerveSpend>()
                .Where(s => KindOfSpend(s) == kind)
                .ToList();

            if (spenders.Count > 0)
            {
                W("**Pluck spenders**");
                W("");
                W("| Spender | Cost | Starts held |");
                W("|---|---|---|");

                foreach (var spend in spenders)
                {
                    var entry = Kits.EntryOf(spend);
                    W("| " + Verve.NameOf(spend)
                        + " | " + Verve.CostOf(spend)
                        + " | " + (kit.Spenders.Contains(entry) ? "yes" : "—") + " |");
                }

                W("");
            }

            int techniques = TechniqueDefinition.All().Count(t => t.Kind == kind);
            int mods = CampCatalogue.ModPool().Count(m => CampCatalogue.KindOf(m) == kind);
            int winds = CampCatalogue.SecondWindPool().Count(s => CampCatalogue.KindOf(s) == kind);
            int unlocks = CampCatalogue.UnlockPool().Count(u => UpgradeDefinition.For(u).Kind == kind);
            int legendaries = LegendaryCatalogue.All().Count(l => l.Class == kind);

            W("**Cards addressed to it:** " + techniques + " techniques · " + mods + " mods · "
                + winds + " Second Winds · " + unlocks + " unlocks · " + legendaries + " legendaries");
            W("");
        }

        W("### What is thin");
        W("");

        foreach (var kind in Classes)
        {
            var kit = Kits.For(kind);
            int known = AbilityDefinition.AllForKind(kind).Count + (Kits.BasicFor(kind) is null ? 0 : 1);
            int held = kit.Abilities.Count;

            W("- **" + Naming.Of(kind) + "** knows " + known + " abilities, holds " + held
                + " of " + kit.AbilitySlots + " slots"
                + (known <= held
                    ? " — and there is **nothing it could learn**, so its ability slots can only ever be filled the way they start."
                    : " — " + (known - held) + " learnable."));
        }

        int learnable = Classes.Sum(k =>
            Math.Max(0, AbilityDefinition.AllForKind(k).Count + (Kits.BasicFor(k) is null ? 0 : 1)
                - Kits.For(k).Abilities.Count));

        W("");
        W("**There are " + learnable + " learnable abilities in the whole game** — at most one per"
            + " class, and none at all for the Archer. Kit surgery's Learn/Replace is built; for"
            + " abilities it has one card per duck to act on, and then it is finished for the run.");

        W("");
    }

    /// <summary>A basic attack's reach, as a band when it has one.</summary>
    private static string Reach(UnitTemplate template) =>
        template.Attack == AttackKind.Melee ? "melee"
            : template.HasSweetSpot ? template.MinRange + "–" + template.Range
            : template.Range.ToString();

    private static string RangeOf(AbilityDefinition def) =>
        def.Range == 0 ? "self"
            : def.MinRange > 0 ? def.MinRange + "–" + def.Range
            : def.Range.ToString();

    private static UnitKind KindOfSpend(VerveSpend spend)
    {
        try
        {
            return Kits.KindOf(Kits.EntryOf(spend));
        }
        catch (Exception)
        {
            return UnitKind.Husk;
        }
    }

    // ---- The card pools ------------------------------------------------------------------------

    private static void Techniques(Action<string> W)
    {
        W("## Techniques — the v2 camp pool");
        W("");
        W("The only camp category that carries a rarity and offer-validity tags of its own. Tags are");
        W("what the Forge's connector requirement reads.");
        W("");
        W("| Technique | Class | Tier | Tags | On | What it does |");
        W("|---|---|---|---|---|---|");

        foreach (var t in TechniqueDefinition.All().OrderBy(t => t.Kind).ThenBy(t => t.Name))
        {
            W("| " + t.Name + " | " + Naming.Of(t.Kind) + " | " + t.Rarity + " | " + Tags(t.Tags)
                + " | " + Kits.NameOf(t.Host) + " | " + t.Summary + " |");
        }

        W("");
        W("### What is thin");
        W("");

        foreach (TechniqueTag tag in Enum.GetValues(typeof(TechniqueTag)))
        {
            if (tag == TechniqueTag.None)
            {
                continue;
            }

            int n = TechniqueDefinition.All().Count(t => (t.Tags & tag) != 0);
            if (n <= 1)
            {
                W("- **" + tag + " has " + (n == 0 ? "nothing" : "one card") + ".** A tag the Forge can"
                    + " ask for and the pool cannot answer is a connector requirement that cannot be met.");
            }
        }

        W("");
    }

    private static string Tags(TechniqueTag tags)
    {
        var names = Enum.GetValues(typeof(TechniqueTag)).Cast<TechniqueTag>()
            .Where(t => t != TechniqueTag.None && (tags & t) != 0)
            .Select(t => t.ToString())
            .ToList();

        return names.Count == 0 ? "—" : string.Join(" · ", names);
    }

    private static void Mods(Action<string> W)
    {
        W("## Mods — cheaper, stronger, or a different economy");
        W("");
        W("Each hangs on one spender and moves one axis of it.");
        W("");
        W("| Mod | Class | On | Axis | What it does |");
        W("|---|---|---|---|---|");

        foreach (var mod in CampCatalogue.ModPool())
        {
            var def = UpgradeDefinition.For(mod);
            // Through the definition's own Host rather than CampCatalogue.SpenderOf, which throws for
            // a mod that hangs on something other than a Pluck spender.
            W("| " + def.Name
                + " | " + (def.Kind is { } k ? Naming.Of(k) : "—")
                + " | " + (def.Host is { } host ? Kits.NameOf(host) : "—")
                + " | " + def.Mechanic
                + " | " + def.Summary + " |");
        }

        W("");
        W("### What is thin");
        W("");

        var byHost = CampCatalogue.ModPool()
            .GroupBy(m => UpgradeDefinition.For(m).Host)
            .OrderBy(g => g.Count())
            .ToList();

        W("- **Mods are the deepest pool by far** — " + CampCatalogue.ModPool().Count
            + " of the camp's " + CampPoolSize() + " cards. Every other category is single digits per class.");

        foreach (var kind in Classes)
        {
            int n = CampCatalogue.ModPool().Count(m => CampCatalogue.KindOf(m) == kind);
            W("  - " + Naming.Of(kind) + ": " + n);
        }

        if (byHost.Count > 0)
        {
            W("- **Thinnest hosts:** "
                + string.Join(" · ", byHost.Take(3).Select(g =>
                    (g.Key is { } h ? Kits.NameOf(h) : "—") + " (" + g.Count() + ")"))
                + ". A duck holding one of these sees the same handful every camp.");
        }

        W("");
    }

    private static void SecondWinds(Action<string> W)
    {
        W("## Second Winds — new ways to earn Pluck");
        W("");
        W("| Second Wind | Class | What charges it |");
        W("|---|---|---|");

        foreach (var wind in CampCatalogue.SecondWindPool())
        {
            var def = UpgradeDefinition.For(wind);
            W("| " + def.Name + " | " + (def.Kind is { } k ? Naming.Of(k) : "any") + " | " + def.Summary + " |");
        }

        W("");
    }

    private static void Unlocks(Action<string> W)
    {
        W("## Unlocks — one sentence of rule, per duck");
        W("");
        W("| Unlock | Class | The sentence |");
        W("|---|---|---|");

        foreach (var unlock in CampCatalogue.UnlockPool())
        {
            var def = UpgradeDefinition.For(unlock);
            W("| " + def.Name + " | " + (def.Kind is { } k ? Naming.Of(k) : "any") + " | " + def.Summary + " |");
        }

        W("");
        W("### What is thin");
        W("");

        int classed = CampCatalogue.UnlockPool().Count(u => UpgradeDefinition.For(u).Kind is not null);
        if (classed == 0)
        {
            W("- **Every unlock is class-agnostic.** All " + CampCatalogue.UnlockPool().Count
                + " read the same on any duck, so an unlock never says anything about who is holding it.");
        }

        W("");
    }

    private static void Consumables_(Action<string> W)
    {
        W("## Items — the pocket");
        W("");
        W("**One pocket per duck.** Use is 0 AP, free-timing inside that duck's own activation, and");
        W("one-shot. A pocket already carrying something is a pocket that must be spent before it can");
        W("be refilled, which is what makes an item a decision rather than a stat.");
        W("");
        W("| Item | Aim | What it does | In the camp pool |");
        W("|---|---|---|---|");

        var pool = CampCatalogue.ConsumablePool();

        foreach (var def in ConsumableDefinition.All())
        {
            W("| " + def.Name
                + " | " + def.Aim
                + " | " + def.Summary
                + " | " + (pool.Contains(def.Item) ? "yes" : "—") + " |");
        }

        W("");
        W("### What is thin");
        W("");

        int offPool = ConsumableDefinition.All().Count(d => !pool.Contains(d.Item));
        if (offPool > 0)
        {
            W("- **" + offPool + " item(s) exist but are not drawable at a camp** — they are built rules"
                + " with no way into a run.");
        }

        W("- **No legendary consumable is built.** The Sunken Cache's mark is typed, named and"
            + " deliberately unpayable, so it draws no gilt edge and hands over nothing.");
        W("");
    }

    private static void Legendaries(Action<string> W)
    {
        W("## Legendaries — destinations only");
        W("");
        W("Never in a camp. A legendary comes from a gilt-marked node, the Molt, or a Strait bargain,");
        W("and a gilt edge means one is **literally there** — promise, not probability.");
        W("");
        W("| Legendary | Class | Tier | What it does |");
        W("|---|---|---|---|");

        foreach (var card in LegendaryCatalogue.All())
        {
            W("| " + card.Name + " | " + Naming.Of(card.Class) + " | " + card.Tier + " | " + card.Summary + " |");
        }

        W("");
        W("### What is thin");
        W("");

        foreach (var kind in Classes)
        {
            int n = LegendaryCatalogue.All().Count(l => l.Class == kind);
            if (n <= 1)
            {
                W("- **" + Naming.Of(kind) + " has " + (n == 0 ? "no legendary" : "one legendary")
                    + "** — a pick-1-of-2 that draws for this duck cannot show it two.");
            }
        }

        W("");
    }

    // ---- The counts, in one place --------------------------------------------------------------

    private static void Totals(Action<string> W)
    {
        W("## Everything, counted");
        W("");
        W("| | Vanguard | Archer | Fisher | Wardbearer | Any | Total |");
        W("|---|---|---|---|---|---|---|");

        Row(W, "Abilities",
            k => AbilityDefinition.AllForKind(k).Count + (Kits.BasicFor(k) is null ? 0 : 1),
            0);
        Row(W, "Techniques", k => TechniqueDefinition.All().Count(t => t.Kind == k), 0);
        Row(W, "Mods", k => CampCatalogue.ModPool().Count(m => CampCatalogue.KindOf(m) == k), 0);
        Row(W, "Second Winds",
            k => CampCatalogue.SecondWindPool().Count(s => CampCatalogue.KindOf(s) == k),
            CampCatalogue.SecondWindPool().Count(s => UpgradeDefinition.For(s).Kind is null));
        Row(W, "Unlocks",
            k => CampCatalogue.UnlockPool().Count(u => UpgradeDefinition.For(u).Kind == k),
            CampCatalogue.UnlockPool().Count(u => UpgradeDefinition.For(u).Kind is null));
        Row(W, "Legendaries", k => LegendaryCatalogue.All().Count(l => l.Class == k), 0);

        W("| Items (pocket) | — | — | — | — | " + ConsumableDefinition.All().Count
            + " | " + ConsumableDefinition.All().Count + " |");
        W("");
        W("**The whole camp pool is " + CampPoolSize() + " cards** across "
            + CampCatalogue.DrawableCategories().Count + " drawable categories.");
        W("");
        W("## What one run actually sees");
        W("");
        W("The authored act gives a route **4–6 combat nodes**, so **4–6 camps**. One pick per player");
        W("per camp is **4–6 cards each, 8–12 for the party** — out of " + CampPoolSize() + ".");
        W("");
        W("**A run meets under a fifth of the pool, and each duck meets far less than that**, because a");
        W("card is addressed to one duck and most of the pool is mods hanging off a spender that duck");
        W("may not even hold. Two runs on the same seed diverge on the first pick; two runs on different");
        W("seeds have almost nothing in common. Whether that reads as variety or as noise is the");
        W("question a playtest answers, and it is worth asking before the pool grows.");
        W("");
        W("## Where the room is");
        W("");
        W("Counted, not felt — each of these is a number above rather than an opinion:");
        W("");
        W("1. **Ability learning runs out after one card.** Three classes have exactly one ability they");
        W("   do not start with; the Archer has none. So kit surgery's Learn/Replace fires once per duck");
        W("   at most, and an Archer's third slot can never be filled by anything. A second learnable");
        W("   ability per class is the cheapest change with the largest effect on what a build can be.");
        W("2. **The Fisher has no legendary** and the other three have one each — so a pick-1-of-2 at a");
        W("   gilt node cannot show two for any duck, and cannot show anything for a Fisher.");
        W("3. **Unlocks are three cards and none of them is about a class.** §8.6 calls them");
        W("   \"one-sentence rule additions per duck\"; today they are the same sentence for everyone.");
        W("4. **Two technique tags are unanswerable.** The Forge reads tags as a connector requirement;");
        W("   Finish has no card at all and Traffic and Control have one each.");
        W("5. **Mods are 32 of 61 cards** — over half the camp is one category, and it is the category");
        W("   that tunes a number rather than changing what a duck can do.");
        W("6. **The Molt is not built**, so nothing survives a run. Every run starts from the same duck");
        W("   and the permanence layer the whole dynasty fiction rests on is absent.");
        W("");
    }

    private static void Row(Action<string> W, string label, Func<UnitKind, int> count, int any)
    {
        var cells = Classes.Select(count).ToList();
        W("| " + label + " | " + string.Join(" | ", cells) + " | " + (any == 0 ? "—" : any.ToString())
            + " | " + (cells.Sum() + any) + " |");
    }

    private static int CampPoolSize() =>
        CampCatalogue.ModPool().Count
        + CampCatalogue.SecondWindPool().Count
        + CampCatalogue.UnlockPool().Count
        + CampCatalogue.ConsumablePool().Count
        + CampCatalogue.TechniquePool().Count;

    private static string RepoRoot()
    {
        var dir = new DirectoryInfo(AppContext.BaseDirectory);
        while (dir is not null && !File.Exists(Path.Combine(dir.FullName, "CLAUDE.md")))
        {
            dir = dir.Parent;
        }

        return dir?.FullName ?? ".";
    }
}
